// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyRestfulApp.DbContexts;

namespace MyRestfulApp.Migrations
{
    [DbContext(typeof(MyRestfulAppContext))]
    [Migration("20211028145457_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MyRestfulApp.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d28888e9-2ba9-473a-a40f-e38cb54f9b35"),
                            Apellido = "Gallardo",
                            Email = "mgallardo@gmail.com",
                            Nombre = "Marcelo",
                            Password = "mgallardo2021"
                        },
                        new
                        {
                            Id = new Guid("da2fd609-d754-4feb-8acd-c4f9ff13ba96"),
                            Apellido = "Armani",
                            Email = "farmani@gmail.com",
                            Nombre = "Franco",
                            Password = "farmani2021"
                        },
                        new
                        {
                            Id = new Guid("2902b665-1190-4c70-9915-b9c2d7680450"),
                            Apellido = "Rojas",
                            Email = "rrojas@gmail.com",
                            Nombre = "Robert",
                            Password = "rrojas2021"
                        },
                        new
                        {
                            Id = new Guid("102b566b-ba1f-404c-b2df-e2cde39ade09"),
                            Apellido = "Peña Biafore",
                            Email = "fbiafore@gmail.com",
                            Nombre = "Felipe",
                            Password = "fbiafore2021"
                        },
                        new
                        {
                            Id = new Guid("5b3621c0-7b12-4e80-9c8b-3398cba7ee05"),
                            Apellido = "Martinez",
                            Email = "hmartinez@gmail.com",
                            Nombre = "Hector",
                            Password = "hmartinez2021"
                        },
                        new
                        {
                            Id = new Guid("2aadd2df-7caf-45ab-9355-7f6332985a87"),
                            Apellido = "Casco",
                            Email = "mcasco@gmail.com",
                            Nombre = "Milton",
                            Password = "mcasco2021"
                        },
                        new
                        {
                            Id = new Guid("2ee49fe3-edf2-4f91-8409-3eb25ce6ca51"),
                            Apellido = "Simon",
                            Email = "ssimon@gmail.com",
                            Nombre = "Santiago",
                            Password = "ssimon2021"
                        },
                        new
                        {
                            Id = new Guid("71838f8b-6ab3-4539-9e67-4e77b8ede1c0"),
                            Apellido = "Fernandez",
                            Email = "efernandez@gmail.com",
                            Nombre = "Enzo",
                            Password = "efernandez2021"
                        },
                        new
                        {
                            Id = new Guid("119f9ccb-149d-4d3c-ad4f-40100f38e918"),
                            Apellido = "Perez",
                            Email = "eperez@gmail.com",
                            Nombre = "Enzo",
                            Password = "eperez2021"
                        },
                        new
                        {
                            Id = new Guid("28c1db41-f104-46e6-8943-d31c0291e0e3"),
                            Apellido = "Palavecino",
                            Email = "apalavecino@gmail.com",
                            Nombre = "Agustin",
                            Password = "apalavecino2021"
                        },
                        new
                        {
                            Id = new Guid("d94a64c2-2e8f-4162-9976-0ffe03d30767"),
                            Apellido = "Alvarez",
                            Email = "jalvarez@gmail.com",
                            Nombre = "Julian",
                            Password = "jalvarez2021"
                        },
                        new
                        {
                            Id = new Guid("380c2c6b-0d1c-4b82-9d83-3cf635a3e62b"),
                            Apellido = "Rollheiser",
                            Email = "brollheiser@gmail.com",
                            Nombre = "Benjamin",
                            Password = "brollheiser2021"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
